pampicture/config/routes.rb
Pampicture::Application.routes.draw do
  
  
  root :to => "pages#home"
  
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "products" => "products#index", :as => "products"
  get "products/:id" => "products#show", :as => "product"
  get "category/:id" => "categories#index", :as => "category"
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :users
  resources :sessions
  

end

pampicture/app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

pampicture/app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  validates :name, :presence => true, :uniqueness => true
end

pampicture/app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :description, :price, :stock_quantity, :category_id, :image
  validates_presence_of :name, :description, :price, :stock_quantity, :category_id
  validates_numericality_of :price, :greater_than_or_equal_to => 0
  validates_numericality_of :stock_quantity, :greater_than_or_equal_to =>0
  validates :name, :uniqueness => true
  belongs_to :category
end

pampicture/app/models/province.rb
class Province < ActiveRecord::Base
  attr_accessible :name, :gst, :pst, :hst
  validates_presence_of :name, :gst, :pst, :hst
  validates_uniqueness_of :name
  validates_numericality_of :pst, :less_than_or_equal_to => 1, :greater_than_or_equal_to =>0
  validates_numericality_of :gst, :less_than_or_equal_to => 1, :greater_than_or_equal_to =>0
  validates_numericality_of :hst, :less_than_or_equal_to => 1, :greater_than_or_equal_to =>0
end

pampicture/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => "create"
  validates_presence_of :email
  validates_uniqueness_of :email
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
end

pampicture/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  private
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

pampicture/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @category = Category.find(params[:id])
    @categories = Category.all
    @products = @category.products
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

end

pampicture/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

pampicture/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @categories = Category.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @category = @product.category
    @categories = Category.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

end

pampicture/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to  root_url, :notice => "Logged out!"
  end
end

pampicture/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to log_in_path, :notice => "Signed up!"
    else
      render "new"
    end
  end
end

pampicture/app/helpers/application_helper.rb
module ApplicationHelper
end

pampicture/app/helpers/categories_helper.rb
module CategoriesHelper
end

pampicture/app/helpers/products_helper.rb
module ProductsHelper
end

pampicture/app/helpers/sessions_helper.rb
module SessionsHelper
end

pampicture/app/helpers/users_helper.rb
module UsersHelper
end

pampicture/app/views/categories/_category.html.erb
<% @categories.each do |category| %>
  <li><%= link_to category.name, category %></li>
<% end %>

pampicture/app/views/categories/index.html.erb
<nav class="side_nav">
  <ul>
    <%= render @category %>
  </ul>
</nav>

<section class="products">
  <h1><%= @category.name %></h1>
   <%= render @products %>
</section>

pampicture/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pampicture</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<section id="wrapper">
  <header id="page_header">
    
    <nav id="user_nav">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <ul>
        <li><%= link_to (image_tag("cart_icon.png") + " Shopping Cart (#)"), "#" %></li>
        <% if current_user %>
          <li><%= link_to "#{current_user.email}", '#' %></li>
          <li><%= link_to "Log out", log_out_path %></li>
        <% else %>
          <li><%= link_to "Log In", log_in_path %></li>
          <li><%= link_to "Sign up", sign_up_path %></li>
        <% end %>
      </ul>
    </nav>
 
    <nav id="main_nav">
      <%= link_to (image_tag("Pampicture_logo.png")), root_path %>
      <ul>
        <li><%= link_to "Home", root_url %></li>
        <li><%= link_to "Products", products_path %></li>
        <li><%= link_to "About", '#' %></li>
        <li><%= link_to "Contact Us", '#' %></li>
      </ul>
    </nav>
    
  </header>
  
  <section id="main">
    <%= yield %>
  </section>
  
  <footer id="page_footer">
    
    <article id="social_media">
      <nav id="social_nav">
        <p>follow us</p>
        <ul>
          <li><a href="#" onclick="return false;"><img src="/assets/facebook_icon.png" /></a></li>
          <li><a href="#" onclick="return false;"><img src="/assets/twitter_icon.png" /></a></li>
          <li><a href="#" onclick="return false;"><img src="/assets/blogger_icon.png" /></a></li>
          <li><a href="#" onclick="return false;"><img src="/assets/sharethis_icon.png" /></a></li>
        </ul>
      </nav>
    <p>COPYRIGHT &copy; 2012 PAMPICTURE&trade;</p>
    </article>
    
    
  </footer>
  
</section>

</body>
</html>

pampicture/app/views/pages/home.html.erb


<h1>PAMPICTURE E-COMMERCE STORE COMING SOON!</h1>

<p>Meanwhile, feel free to browse our products</p>



pampicture/app/views/products/_product.html.erb
<section class="product_partial">

  <p id="notice"><%= notice %></p>

  <section class="left">
    <%= link_to image_tag(product.image, :width => "140px"), product %>
    <p><%= link_to product.name, product %></p>
  </section>
  
  <section class="right">
    <p><%= number_to_currency product.price, :unit => "&dollar;" %></p>
    <%= link_to "Add to Cart", "#" %>
  </section>
  
</section>

pampicture/app/views/products/index.html.erb
<% @categories.each do |category| %>
<section class="four_products">
<h1><%= category.name %><%= link_to "View more", category %></h1>
  <nav>
    <ul>
      <% 4.times do |num| %>
      <li>
        <% product = category.products[num] %>    
        <%= link_to image_tag(product.image, :width => "140"), product %>
        <p><%= link_to product.name, product %></p>
      </li>
      <% end %>
    </ul>
  </nav>
</section>
<% end %>

pampicture/app/views/products/show.html.erb
<nav class="side_nav">
  <ul>
    <%= render @category %>
  </ul>
</nav>

<section class="products">
  <h1><%= @category.name %></h1>
  
  <%= render @product %>
  
  <p class="description">
    <%= @product.description %>
  </p>
</section>

pampicture/app/views/users/new.html.erb
<section id="sign_up">
  <h1>Sign Up</h1>
  
  <%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit "Sign Up" %></p>
  <% end %>
</section>